// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://fromkeith.com",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gmail/inbox": {
            "get": {
                "description": "List the user's email inbox",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "List the inbox",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/GmailEntry"
                            }
                        }
                    }
                }
            }
        },
        "/gmail/message/:messageId": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "Get the basic information about a message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GmailEntry"
                        }
                    }
                }
            }
        },
        "/gmail/message/:messageId/contents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "Get the contents of a message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GmailEntryBody"
                        }
                    }
                }
            }
        },
        "/gmail/thread/{threadId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "List all messages in a thread",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/GmailEntry"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GmailEntry": {
            "type": "object",
            "required": [
                "additionalReceivers",
                "headers",
                "historyId",
                "internalDate",
                "labels",
                "messageId",
                "receivedAt",
                "receiver",
                "sender",
                "snippet",
                "subject",
                "threadId",
                "userId"
            ],
            "properties": {
                "additionalReceivers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/PersonInfo"
                        }
                    }
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "historyId": {
                    "type": "integer"
                },
                "internalDate": {
                    "type": "integer"
                },
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "messageId": {
                    "type": "string"
                },
                "receivedAt": {
                    "type": "string"
                },
                "receiver": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/PersonInfo"
                    }
                },
                "replyTo": {
                    "$ref": "#/definitions/PersonInfo"
                },
                "sender": {
                    "$ref": "#/definitions/PersonInfo"
                },
                "snippet": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "threadId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "GmailEntryBody": {
            "type": "object",
            "required": [
                "hasAttachments",
                "messageId",
                "userId"
            ],
            "properties": {
                "attachmentIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hasAttachments": {
                    "type": "integer"
                },
                "html": {
                    "type": "string"
                },
                "messageId": {
                    "type": "string"
                },
                "plainText": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "PersonInfo": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5173",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Desktop Eamil",
	Description:      "API Calls",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
