# https://taskfile.dev

version: "3"

tasks:
    build-server:
        env:
            CGO_ENABLED: 1
        cmds:
            - go build -tags=jsoniter .
    build-injestor:
        cmds:
            - go build ./services/email-injestor
    build-gemini:
        cmds:
            - go build ./services/gemini

    run-server:
        deps:
            - build-server
        cmds:
            - ./my-desktop-server
    run-injestor:
        deps:
            - build-injestor
        cmds:
            - ./email-injestor
    run-gemini:
        deps:
            - build-gemini
        cmds:
            - ./gemini

    migrate-postgres:
        cmds:
            - dbmate -d ./migrations -u postgres://postgres:postgres@localhost:5432/desktop?sslmode=disable up
    migrate-mongo:
        cmds:
            - cd migrations/mongo && migrate-mongo up
    # eg: task migrate-mongo-create -- cliargshere
    migrate-mongo-create:
        cmds:
            - cd migrations/mongo && migrate-mongo create {{.CLI_ARGS}}

    up:
        cmds:
            - docker-compose up -d
    down:
        cmds:
            - docker-compose down

    run-all:
        deps:
            - run-server
            - run-injestor
            - run-gemini
